### ISSUE TITLE
help please

### ISSUE THREAD

**Issue by weedking12** [NapoleonWils0n/kodi-playercorefactory#10]
hi there watched your great how to vids but how can i find links from kodi im on windows 10 64bit really 
stuck can you help me please thanks

**Comment by NapoleonWils0n** [comment]
HI Mate
What do you mean by "links"
Need to be more specific, have you installed everything which bit isnt working

**Comment by weedking12** [comment]
hi there i watched all your video on youtube and get bash error when try to
record or use other player only thing works is save url

**Comment by nunutpe** [comment]
Hi ! everying is going well but how to record my own tv channel .
many thanks !

**Comment by NapoleonWils0n** [comment]
HI weedking12
I have updated the windows script which should fix the issue, do a git pull to update

After updating windows 10 in my virtual machine the scripts stopped working for me and i had to alter the scripts to get them working again, by specifying the full path to the video-regex.sh in the scripts.

i have also added mpv as an external player

make sure to read the windows read me page on how to set up mpv
https://github.com/NapoleonWils0n/kodi-playercorefactory/tree/master/windows

make sure to copy the new playercorefactory.xml to your kodi userdata folder

let me know if the update fixes the issue

**Comment by NapoleonWils0n** [comment]
Hi nunutpe
Have you got the stream for you tv channel working in kodi ?

You can create a .m3u or .plx file with the video url and add it to the playlist loader addon

or you can create a .strm text file and add the url to that
http://kodi.wiki/view/Internet_video_and_audio_streams

**Comment by weedking12** [comment]
still getting bash error on record but when open vlc or extrnal player now
nothing happens still only one works save url so hard this to figure out

**Comment by NapoleonWils0n** [comment]
HI weedking12 

sorry your having problems getting set up
have you followed all the steps in the windows read me page

https://github.com/NapoleonWils0n/kodi-playercorefactory/tree/master/windows

you need to install cygwin, and make sure to install sed, grep and wget with cygwin

also install git and set Checkout as--is, commit Unix-style line endings
install ffmpeg, rtmpdump, vlc, mpv and set up your windows system path

check you have installed software to the same location as the windows read and you dont have any typos in your windows system path

**Comment by weedking12** [comment]
mate i have tried and tried followed your vids still errror

**Comment by NapoleonWils0n** [comment]
Hi weedking12

Sorry your having grief getting set up mate,
try not to get frustrated 

I have had old age pensioners using windows 7 manged to get this working, so it does work on windows 7 and up including windows 10 ( i dont mean that as an insult mate )

i can only suggest starting from scratch and installing everything a little bit at a time
i know thats a pain 

if you follow the steps on the windows readme a bit at a time it should work

https://github.com/NapoleonWils0n/kodi-playercorefactory/tree/master/windows

im not a windows user so i dont know why it isnt working for you 

the only other thing i can suggest is to use linux as it takes about 5 minutes to get everything installed, it is possible to install linux and grub on an external hard drive

i may actually do some videos on setting up kodi and all the scripts on linux soon

unfortunately it takes a lot more work to install everything on windows, than it does on linux or macosx

as i said the only thing i can suggest is to follow the windows read me slowly step by step and reinstall everything, there may be something you missed

i have spent many an hour trying to fix something and it was just a typo, so its not just you mate

**Comment by weedking12** [comment]
cheers will try again mate thanks its hard for me as have fibomyaliga cant
use hand and walk good and sezuires thanks for all you help
